kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: container-exporter
  namespace: kubesphere-monitoring-system
  labels:
    app: container-exporter
spec:
  selector:
    matchLabels:
      app: container-exporter
  template:
    metadata:
      labels:
        app: container-exporter
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: host-sock
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: ''
        - name: host-proc
          hostPath:
            path: /proc
            type: ''
      containers:
        - name: container-w8jeoo
          image: 'reposc.cloud.test/kubesphere/container-exporter:v0.1.7'
          ports:
            - name: containerexport
              hostPort: 9090
              containerPort: 9090
              protocol: TCP
          env:
            - name: NODE_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: host-sock
              readOnly: true
              mountPath: /host/var/run/containerd/containerd.sock
            - name: host-proc
              readOnly: true
              mountPath: /host/proc
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - operator: Exists
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10

