apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: container-exporter
    app.kubernetes.io/part-of: container-port
  name: container-exporter
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - interval: 10s
    metricRelabelings:
    - action: replace
      sourceLabels:
      - exported_namespace
      targetLabel: namespace
    - action: replace
      sourceLabels:
      - exported_container
      targetLabel: container
    - action: replace
      sourceLabels:
      -  exported_pod
      targetLabel: pod
    - action: labeldrop
      regex: exported_.*
    port: container-export
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - kubesphere-monitoring-system
  selector:
    matchLabels:
      app: container-exporter

